const assert = require("node:assert/strict")
const fs = require("node:fs")
const path = require("node:path")

const root = path.resolve(__dirname, "..")
const read = relativePath => fs.readFileSync(path.join(root, relativePath), "utf8")

const ai = read("js/06-menu-ai.js")
const training = read("js/06-menu-ai-training.js")
const input = read("js/09-input.js")
const tower = read("js/03-tower.js")
const projectile = read("js/04-support-entities.js")
const mainLoop = read("js/08-main-loop.js")
const endpoint = read("ai-learning.php")
const accessRules = read("data/.htaccess")
const endpointTest = read("tools/test-ai-endpoint.js")
const index = read("index.html")
const styles = read("styles.css")
const distributedCommon = read("tools/distributed-ai/common.js")
const distributedWorker = read("tools/distributed-ai/run-worker.js")
const distributedSelect = read("tools/distributed-ai/select-candidate.js")
const hostedModelTool = read("tools/distributed-ai/hosted-model.js")
const trainingWorkflow = read(".github/workflows/ai-training.yml")
const manualPromotionWorkflow = read(".github/workflows/ai-promote.yml")
const watchdogWorkflow = read(".github/workflows/ai-training-watchdog.yml")
const manualAimAction = ai.slice(ai.indexOf("function advanceAIManualAimAction"), ai.indexOf("function getAIAimSnapshot"))
const animate = mainLoop.slice(mainLoop.indexOf("function animate()"))

assert.match(ai, /AI_LEARNING_SCHEMA_VERSION = 9/)
assert.match(ai, /AI_MODEL_FAMILY = "shared-neural-controller-v1"/)
assert.match(ai, /AI_POLICY_HIDDEN_SIZE_1 = 64/)
assert.match(ai, /AI_POLICY_HIDDEN_SIZE_2 = 32/)
assert.match(ai, /AI_DECISION_STATE_INPUT_SIZE = 48/)
assert.match(ai, /AI_DECISION_CANDIDATE_INPUT_SIZE = 32/)
assert.match(ai, /AI_MAX_PUBLIC_DECISION_SAMPLES = 32/)
assert.match(ai, /AI_MAX_DECISION_SAMPLE_AGE = 1000000/)
assert.match(ai, /AI_POLICY_PARAMETER_LIMIT = 4/)
assert.match(ai, /target = clamp\(reward, -0\.98, 0\.98\)/)
assert.match(ai, /outputDelta = error \* \(1 - prediction \* prediction\)/)
assert.match(ai, /clampAIPolicyParameter\(/)
assert.doesNotMatch(ai, /return clamp\(reward, -2\.1, 1\.6\)/)
assert.match(ai, /trainAIPolicy\(aiMatchTelemetry\.selectionFeatures/)
assert.match(ai, /function aiDecisionForward\(/)
assert.match(ai, /function trainAIDecision\(/)
assert.match(ai, /function scoreAIDecisionCandidate\(/)
assert.match(ai, /decisionSamples: decisionSamples/)
assert.match(ai, /getAIDecisionBootstrapWeight\(familyIndex, policyOverride\) \* 2\.5/)
assert.doesNotMatch(ai, /getAIDecisionBootstrapWeight\(\)/)
assert.match(ai, /trainingSamples: aiCreateVector\(AI_DECISION_FAMILY_COUNT, 0\)/)
assert.match(ai, /decision\.trainingSamples\[familyIndex\]\+\+/)
assert.match(ai, /function recordAINoOpDecision\(/)
assert.match(ai, /familyCounts\[countIndex\] > 1/)
assert.doesNotMatch(ai, /canAIInvestInFarmNow/)
assert.match(ai, /function migrateAIPolicy\(/)
assert.match(ai, /AI_CONTRIBUTION_STORAGE_KEY = "aiPendingContributionsV1"/)
assert.match(ai, /function queueAIPublicContribution\(/)
assert.match(ai, /function flushAIPublicContributionQueue\(/)
assert.match(ai, /createAIPublicMatchContribution\(aiLives, enemyLives, reward, matchFeatures, selfPlayActive\)/)
assert.match(ai, /queueAIPublicContribution\(publicContribution\)/)
assert.match(ai, /return isValidAIPolicy\(aiLearning\.policy\) \? aiLearning\.policy : aiLearning\.championPolicy/)
assert.match(ai, /eventType: "human-demo-v1"/)
assert.match(ai, /function updateLocalMatchCollectionTelemetry\(/)
assert.match(ai, /function finalizeLocalMatchCollection\(/)
assert.match(ai, /function discardStaleAIPublicContributions\(/)
assert.match(ai, /contributionEpoch: Math\.max\(1, Math\.floor\(localMatchCollectionState\.contributionEpoch\)\)/)
assert.match(ai, /contributionEpoch: Math\.max\(1, Math\.floor\(aiMatchTelemetry\.contributionEpoch\)\)/)
assert.match(ai, /function applyAILearningEnvelope\(/)
assert.match(ai, /aiPersistenceState\.updatedAt = typeof parsed\.updatedAt/)
assert.match(ai, /incomingEpoch < aiPersistenceState\.contributionEpoch \|\| incomingEpoch == aiPersistenceState\.contributionEpoch && incomingRevision < aiPersistenceState\.revision/)
assert.match(ai, /aiLearningRefreshForceQueued = true/)
assert.match(ai, /code == "contribution_epoch_mismatch"[\s\S]{0,500}refreshAILearningFromBackend\(true\)/)
assert.match(ai, /code == "contribution_revision_stale"[\s\S]{0,700}refreshAILearningFromBackend\(true\)/)
assert.match(ai, /function markAIPublicContributionStatus\(/)
assert.match(ai, /contextTelemetry\.contributionStatus = status/)
assert.match(ai, /localMatchCollectionState\.contributionStatus = leftQueued && rightQueued \? "queued" : "failed"/)
assert.match(ai, /var candidateContext = aiContextsBySide\[aiTrainingState\.candidateSide\]/)
assert.match(ai, /var savedLearningSnapshot = JSON\.parse\(JSON\.stringify\(aiLearning\)\)/)
assert.match(ai, /aiPersistenceState\.revision = Math\.max\(aiPersistenceState\.revision, committedRevision\)/)
assert.match(ai, /var contributionMetadataCurrent = contributionEpoch >= aiPersistenceState\.contributionEpoch && contributionRevision >= aiPersistenceState\.revision/)
assert.match(ai, /selfPlayActive && typeof shouldAITrainingPublishContributions == "function"/)
assert.match(ai, /selectedMenuMode != "local" \|\| aiEnabled \|\| practiceMode \|\| bossMode/)
assert.match(mainLoop, /updateLocalMatchCollectionTelemetry\(\)/)
assert.match(mainLoop, /finalizeLocalMatchCollection\(\)/)
assert.match(mainLoop, /getCompletedMatchAIRematchMessage\(\)/)

assert.match(ai, /championPolicy: cloneAIPolicy\(candidatePolicy\)/)
assert.match(ai, /populationPolicies: \[\]/)
assert.match(training, /policySnapshot: opponentPolicy/)
assert.match(training, /learningEnabled: false/)
assert.match(training, /candidateTrainingMatches >= 128/)
assert.match(training, /evaluationGames >= 64/)
assert.match(training, /score >= 0\.58/)
assert.match(training, /return \{ label: "Session Only", disabled: true, action: "none" \}/)
assert.match(training, /return \{ label: "Refreshing\.\.\.", disabled: true, action: "none" \}/)
assert.match(training, /return \{\s*label: "Live Eval"/)
assert.match(training, /if\(counts\[i\] > 0\)/)
assert.match(training, /aiTrainingState\.trueSelfPlayMatches >= getAITrainingGoalEpisodes\(\)/)
assert.match(training, /function installAITrainingHostedLearning\(/)
assert.match(training, /function activateAITrainingSessionModel\(/)
assert.match(training, /function deactivateAITrainingSessionModel\(/)
assert.match(training, /function getAITrainingPersistenceMode\(/)
assert.match(training, /function shouldAITrainingPublishContributions\(/)
assert.match(training, /aiTrainingState\.persistenceMode = persistenceMode/)
assert.match(training, /Model: Temporary ~19k Neural Controller/)
assert.match(training, /return AI_CROSS_MATCH_LEARNING_ENABLED && aiPersistenceState\.contributionEnabled \? "contributions" : "session"/)
assert.doesNotMatch(training, /return "snapshot"/)
assert.match(training, /aiLearning\.policy = cloneAIPolicy\(aiLearning\.championPolicy\)/)
assert.match(training, /scenarioIndex = aiTrainingState\.trueSelfPlayMatches % 8/)
assert.match(training, /candidateSide = Math\.floor\(scenarioIndex \/ 2\) % 2 == 0/)
assert.match(training, /candidateResponds = Math\.floor\(scenarioIndex \/ 4\) % 2 == 0/)
assert.match(training, /aiTrainingState\.candidateResponds = candidateResponds/)
assert.doesNotMatch(training, /chooseAITrainingRandomLoadout|chooseAITrainingBestLoadout|forcedLoadout/)
assert.match(training, /primeAITrainingTrueSelfPlayContext\(probeSide, null, null, probePolicyConfig\)/)
assert.match(distributedWorker, /candidateRole: aiTrainingState\.candidateResponds \? "responder" : "probe"/)
assert.match(distributedWorker, /validatePolicyOnlyCandidate\(checkpoint, baseline\)/)
assert.match(distributedSelect, /requiredArg\(args, "baseline"\)/)
assert.match(distributedSelect, /materializePolicyOnlyCandidate\(selected, baseline\)/)
assert.match(distributedCommon, /model\.championPolicy = clone\(selectedPolicy\)/)
assert.match(distributedCommon, /byRole: roles/)
assert.match(distributedCommon, /expectedCoverage\.balanced/)

assert.match(ai, /return aiPlaceTower\([\s\S]*?!= null/)
assert.match(ai, /directUpgradeSucceeded = aiTryUpgradeTower\(/)
assert.match(ai, /return directUpgradeSucceeded/)
assert.match(ai, /function isAITrainingDirectAIActionMode\(\)[\s\S]{0,180}isAITrainingTrueSelfPlayActive\(\)/)
assert.doesNotMatch(ai, /function isAITrainingDirectAIActionMode\(\) \{\s*return gameStarted/)
assert.match(ai, /manualAimAction: null/)
assert.match(manualAimAction, /getSelectedTower\(side\) != tower/)
assert.match(manualAimAction, /updateTowerTargetPriority\(tower, 1\)/)
assert.match(mainLoop, /function updateManualAimTowerTargets\(\)/)
assert.match(animate, /updateManualAimTowerTargets\(\)/)
assert.doesNotMatch(ai, /function lockTowerAimToCursor\(/)
assert.match(ai, /towerID: tower\.towerID/)
assert.match(ai, /action\.attempts >= 2/)
assert.match(ai, /currentUpgrade == 4[\s\S]*?hasOtherTier5/)
assert.match(input, /typeof upgradeCost != "number"/)
assert.match(input, /addEventListener\("pointerdown", handleCanvasPointerDown\)/)
assert.doesNotMatch(input, /addEventListener\("mousedown"/)

assert.match(ai, /var noActiveThreat = defenseMath\.requiredDps <= 0/)
assert.match(ai, /aiSelectEcoSend\(side, matchup\)/)
assert.match(ai, /getAITacticalActionBonus\(side, "eco"/)
assert.match(ai, /getAITacticalActionBonus\(side, "rush"/)
assert.match(ai, /getAITacticalActionBonus\(side, tower\.towerType == "farm"/)
assert.match(ai, /finalizeAITacticalLearning\(aiSide, reward\)/)
assert.match(ai, /runAIGameplayDecisionCycle/)
assert.match(training, /runAIGameplayDecisionCycle\(aiSide\)/)

assert.match(ai, /if\(now <= sample\.lastSeenAt\)/)
assert.doesNotMatch(training, /function runAIForActiveContext\(\)[\s\S]{0,500}updateAITowerDamageRates\(\)/)
assert.match(training, /if\(isAITrainingTrueSelfPlayActive\(\)\) \{\s*updateAITowerDamageRates\(\)/)

assert.match(tower, /var nextTowerID = 1/)
assert.match(tower, /this\.towerID = nextTowerID\+\+/)
assert.doesNotMatch(tower, /this\.towerID = Math\.trunc\(Math\.random/)
assert.match(projectile, /this\.sourceImage = image/)
assert.match(input, /players\[side\]\.money -= baseFarmerPrice/)
assert.match(mainLoop, /p1lives -= 104/)
assert.match(mainLoop, /p2lives -= 104/)

assert.match(endpoint, /AI_MODEL_SCHEMA = 9/)
assert.match(endpoint, /AI_POLICY_FORMAT_VERSION = 2/)
assert.match(endpoint, /AI_MAX_DECISION_SAMPLES = 32/)
assert.match(endpoint, /AI_MAX_CONTRIBUTION_POLICY_DELTA_NORM = 0\.35/)
assert.match(endpoint, /AI_MAX_SAFE_INTEGER = 9007199254740991/)
assert.match(endpoint, /function migrate_legacy_model\(/)
assert.match(endpoint, /function train_candidate_decision\(/)
assert.match(endpoint, /function limit_policy_parameter_delta\(/)
assert.match(endpoint, /function canonical_weight\(/)
assert.match(endpoint, /function canonical_digest_encode\(/)
assert.match(endpoint, /return 's:' \. bin2hex\(\$value\)/)
assert.match(distributedCommon, /bytes\.writeDoubleBE\(item\)/)
assert.match(endpoint, /if \(\$origin === ''\) \{\s*return false;/)
assert.match(endpoint, /expectedRevision/)
assert.match(endpoint, /revision_conflict/)
assert.match(endpoint, /X_AI_TRAINER_KEY/)
assert.match(endpoint, /LOCK_EX/)
assert.match(endpoint, /rename\(\$temporaryFile, \$stateFile\)/)
assert.match(endpoint, /payload_too_large/)
assert.match(endpoint, /action === 'contribute'/)
assert.match(endpoint, /X_AI_CONTRIBUTION_TOKEN/)
assert.match(endpoint, /AI_CONTRIBUTION_RATE_LIMIT = 120/)
assert.match(endpoint, /prepare_contribution_guard\(/)
assert.match(endpoint, /apply_public_contribution\(/)
assert.match(endpoint, /valid_human_demonstration\(/)
assert.match(endpoint, /apply_human_demonstration\(/)
assert.match(endpoint, /totalHumanDemonstrations/)
assert.match(endpoint, /contribution_revision_stale/)
assert.match(endpoint, /normalized_contribution_guard\(\$current\)/)
assert.match(endpoint, /function valid_fresh_model\(/)
assert.match(endpoint, /state_contribution_epoch\(\$current\)/)
assert.match(endpoint, /contribution_epoch_mismatch/)
assert.match(endpoint, /\$action === 'promote'/)
assert.match(endpoint, /HTTP_X_AI_POLICY_PROMOTION_KEY/)
assert.match(endpoint, /function promotion_base_digest\(/)
assert.match(endpoint, /\$candidatePolicyPreserved = model_digest\(\$currentModel\['policy'\]\) !== \$request\['expectedPolicyDigest'\]/)
assert.match(endpoint, /\$nextModel = \$currentModel/)
assert.match(endpoint, /normalized_contribution_guard\(\$current\), \$currentEpoch/)
assert.match(endpoint, /\$action !== 'commit' && \$action !== 'reset'/)
assert.match(endpoint, /\$nextEpoch = state_contribution_epoch\(\$current\) \+ \(\$isKnowledgeReset \? 1 : 0\)/)
assert.match(endpoint, /\$nextGuard = \$isKnowledgeReset \? \['recent' => \[\], 'rates' => \[\]\]/)
assert.match(accessRules, /Require all denied/)
assert.match(endpointTest, /assert\.equal\(migratedState\.revision, 9\)/)
assert.match(endpointTest, /assert\.equal\(migratedState\.contributionEpoch, 4\)/)
assert.match(endpointTest, /createHostedSnapshot\(envelope\)/)
assert.match(endpointTest, /\.status, 429/)
assert.match(endpointTest, /const staleEpoch = createContribution/)
assert.match(endpointTest, /assert\.deepEqual\(migratedChampion\.strategy\.W1\.slice\(0, 12\), legacyModel\.championPolicy\.W1\)/)
assert.match(endpointTest, /assert\.equal\(envelope\.model\.totalDecisionSamples, 1\)/)
assert.match(endpointTest, /assert\.equal\(envelope\.model\.totalHumanDemonstrations, 3\)/)
assert.match(endpointTest, /assert\.deepEqual\(envelope\.model\.policy, candidateBeforeHuman\)/)
assert.match(endpointTest, /assert\.equal\(resetResult\.contributionEpoch, 5\)/)
assert.match(endpointTest, /assert\.equal\(promoteResult\.candidatePolicyPreserved, true\)/)
assert.match(endpointTest, /assert\.equal\(\(await replayPromotion\.json\(\)\)\.duplicate, true\)/)
assert.match(endpointTest, /assert\.equal\(finalEnvelope\.model\.totalDecisionSamples, 4\)/)
assert.match(endpointTest, /assert\.deepEqual\(finalEnvelope\.model\.championPolicy, resetChampion\)/)
assert.match(distributedCommon, /function createHostedSnapshot\(/)
assert.match(distributedCommon, /function buildPolicyPromotionRequest\(/)
assert.match(hostedModelTool, /AI_POLICY_PROMOTION_KEY/)
assert.match(hostedModelTool, /redirect: "error"/)
assert.match(trainingWorkflow, /name: ai-hosted-baseline/)
assert.match(trainingWorkflow, /publish-hosted:/)
assert.match(trainingWorkflow, /--baseline "\$RUNNER_TEMP\/bundle\/baseline\.json"/)
assert.doesNotMatch(trainingWorkflow, /--checkpoint training\/checkpoints\/champion\.json/)
assert.match(manualPromotionWorkflow, /publish-hosted:/)
assert.match(manualPromotionWorkflow, /AI_POLICY_PROMOTION_KEY/)
assert.match(manualPromotionWorkflow, /reconcile_hosted_promotion:/)
assert.match(manualPromotionWorkflow, /mode=reconcile/)
assert.match(watchdogWorkflow, /AI_HOSTED_PROMOTION_ENABLED == 'true'/)
assert.match(watchdogWorkflow, /training_matches=192/)
assert.match(watchdogWorkflow, /Circuit breaker open/)
assert.match(watchdogWorkflow, /matching-refs\/heads\/ai-promotion/)
assert.match(index, /js\/00-constants\.js\?v=2\.6\.0/)
assert.match(index, /meta name="viewport" content="width=device-width, initial-scale=1"/)
assert.match(index, /js\/06-menu-ai\.js\?v=2\.6\.0/)
assert.match(index, /js\/06-menu-ai-training\.js\?v=2\.6\.0/)
assert.match(index, /js\/08-main-loop\.js\?v=2\.6\.0/)
assert.match(styles, /@media \(max-aspect-ratio: 683 \/ 384\)/)
assert.match(styles, /@media \(min-aspect-ratio: 683 \/ 384\)/)
assert.match(styles, /touch-action: none/)

console.log("AI validation passed: schema-9 neural authority, bounded decision learning, full-bundle promotion, and continuous-training safety are present.")
