const assert = require("node:assert/strict")
const fs = require("node:fs")
const path = require("node:path")

const root = path.resolve(__dirname, "..")
const read = relativePath => fs.readFileSync(path.join(root, relativePath), "utf8")

const ai = read("js/06-menu-ai.js")
const training = read("js/06-menu-ai-training.js")
const input = read("js/09-input.js")
const tower = read("js/03-tower.js")
const projectile = read("js/04-support-entities.js")
const mainLoop = read("js/08-main-loop.js")
const endpoint = read("ai-learning.php")
const accessRules = read("data/.htaccess")
const endpointTest = read("tools/test-ai-endpoint.js")
const index = read("index.html")
const distributedCommon = read("tools/distributed-ai/common.js")
const distributedWorker = read("tools/distributed-ai/run-worker.js")
const distributedSelect = read("tools/distributed-ai/select-candidate.js")
const manualAimAction = ai.slice(ai.indexOf("function advanceAIManualAimAction"), ai.indexOf("function getAIAimSnapshot"))
const animate = mainLoop.slice(mainLoop.indexOf("function animate()"))

assert.match(ai, /AI_LEARNING_SCHEMA_VERSION = 8/)
assert.match(ai, /AI_POLICY_PARAMETER_LIMIT = 4/)
assert.match(ai, /target = clamp\(reward, -0\.98, 0\.98\)/)
assert.match(ai, /outputDelta = error \* \(1 - prediction \* prediction\)/)
assert.match(ai, /clampAIPolicyParameter\(/)
assert.doesNotMatch(ai, /return clamp\(reward, -2\.1, 1\.6\)/)
assert.match(ai, /trainAIPolicy\(aiMatchTelemetry\.selectionFeatures/)
assert.match(ai, /AI_CONTRIBUTION_STORAGE_KEY = "aiPendingContributionsV1"/)
assert.match(ai, /function queueAIPublicContribution\(/)
assert.match(ai, /function flushAIPublicContributionQueue\(/)
assert.match(ai, /createAIPublicMatchContribution\(aiLives, enemyLives, reward, matchFeatures, selfPlayActive\)/)
assert.match(ai, /queueAIPublicContribution\(publicContribution\)/)
assert.match(ai, /aiPersistenceState\.contributionEnabled && isValidAIPolicy\(aiLearning\.policy\)/)
assert.match(ai, /eventType: "human-demo-v1"/)
assert.match(ai, /function updateLocalMatchCollectionTelemetry\(/)
assert.match(ai, /function finalizeLocalMatchCollection\(/)
assert.match(ai, /function discardStaleAIPublicContributions\(/)
assert.match(ai, /contributionEpoch: Math\.max\(1, Math\.floor\(localMatchCollectionState\.contributionEpoch\)\)/)
assert.match(ai, /contributionEpoch: Math\.max\(1, Math\.floor\(aiMatchTelemetry\.contributionEpoch\)\)/)
assert.match(ai, /code == "contribution_epoch_mismatch"[\s\S]{0,500}requestAIPublicContributionToken\(\)/)
assert.match(ai, /selectedMenuMode != "local" \|\| aiEnabled \|\| practiceMode \|\| bossMode/)
assert.match(mainLoop, /updateLocalMatchCollectionTelemetry\(\)/)
assert.match(mainLoop, /finalizeLocalMatchCollection\(\)/)

assert.match(ai, /championPolicy: cloneAIPolicy\(candidatePolicy\)/)
assert.match(ai, /populationPolicies: \[\]/)
assert.match(training, /policySnapshot: opponentPolicy/)
assert.match(training, /learningEnabled: false/)
assert.match(training, /evaluationGames >= 32/)
assert.match(training, /score >= 0\.56/)
assert.match(training, /aiLearning\.policy = cloneAIPolicy\(aiLearning\.championPolicy\)/)
assert.match(training, /scenarioIndex = aiTrainingState\.trueSelfPlayMatches % 8/)
assert.match(training, /candidateSide = Math\.floor\(scenarioIndex \/ 2\) % 2 == 0/)
assert.match(training, /candidateResponds = Math\.floor\(scenarioIndex \/ 4\) % 2 == 0/)
assert.match(training, /aiTrainingState\.candidateResponds = candidateResponds/)
assert.match(distributedWorker, /candidateRole: aiTrainingState\.candidateResponds \? "responder" : "probe"/)
assert.match(distributedWorker, /validatePolicyOnlyCandidate\(checkpoint, baseline\)/)
assert.match(distributedSelect, /requiredArg\(args, "baseline"\)/)
assert.match(distributedSelect, /materializePolicyOnlyCandidate\(selected, baseline\)/)
assert.match(distributedCommon, /model\.championPolicy = clone\(selectedPolicy\)/)
assert.match(distributedCommon, /byRole: roles/)
assert.match(distributedCommon, /expectedCoverage\.balanced/)

assert.match(ai, /return aiPlaceTower\([\s\S]*?!= null/)
assert.match(ai, /directUpgradeSucceeded = aiTryUpgradeTower\(/)
assert.match(ai, /return directUpgradeSucceeded/)
assert.match(ai, /function isAITrainingDirectAIActionMode\(\)[\s\S]{0,180}isAITrainingTrueSelfPlayActive\(\)/)
assert.doesNotMatch(ai, /function isAITrainingDirectAIActionMode\(\) \{\s*return gameStarted/)
assert.match(ai, /manualAimAction: null/)
assert.match(manualAimAction, /getSelectedTower\(side\) != tower/)
assert.match(manualAimAction, /updateTowerTargetPriority\(tower, 1\)/)
assert.match(mainLoop, /function updateManualAimTowerTargets\(\)/)
assert.match(animate, /updateManualAimTowerTargets\(\)/)
assert.doesNotMatch(ai, /function lockTowerAimToCursor\(/)
assert.match(ai, /towerID: tower\.towerID/)
assert.match(ai, /action\.attempts >= 2/)
assert.match(ai, /currentUpgrade == 4[\s\S]*?hasOtherTier5/)
assert.match(input, /typeof upgradeCost != "number"/)

assert.match(ai, /var noActiveThreat = defenseMath\.requiredDps <= 0/)
assert.match(ai, /aiSelectEcoSend\(side, matchup\)/)
assert.match(ai, /getAITacticalActionBonus\(side, "eco"/)
assert.match(ai, /getAITacticalActionBonus\(side, "rush"/)
assert.match(ai, /getAITacticalActionBonus\(side, tower\.towerType == "farm"/)
assert.match(ai, /finalizeAITacticalLearning\(aiSide, reward\)/)
assert.match(ai, /runAIGameplayDecisionCycle/)
assert.match(training, /runAIGameplayDecisionCycle\(aiSide\)/)

assert.match(ai, /if\(now <= sample\.lastSeenAt\)/)
assert.doesNotMatch(training, /function runAIForActiveContext\(\)[\s\S]{0,500}updateAITowerDamageRates\(\)/)
assert.match(training, /if\(isAITrainingTrueSelfPlayActive\(\)\) \{\s*updateAITowerDamageRates\(\)/)

assert.match(tower, /var nextTowerID = 1/)
assert.match(tower, /this\.towerID = nextTowerID\+\+/)
assert.doesNotMatch(tower, /this\.towerID = Math\.trunc\(Math\.random/)
assert.match(projectile, /this\.sourceImage = image/)
assert.match(input, /players\[side\]\.money -= baseFarmerPrice/)
assert.match(mainLoop, /p1lives -= 104/)
assert.match(mainLoop, /p2lives -= 104/)

assert.match(endpoint, /AI_MODEL_SCHEMA = 8/)
assert.match(endpoint, /expectedRevision/)
assert.match(endpoint, /revision_conflict/)
assert.match(endpoint, /X_AI_TRAINER_KEY/)
assert.match(endpoint, /LOCK_EX/)
assert.match(endpoint, /LOCK_SH/)
assert.match(endpoint, /rename\(\$temporaryFile, \$stateFile\)/)
assert.match(endpoint, /payload_too_large/)
assert.match(endpoint, /action === 'contribute'/)
assert.match(endpoint, /X_AI_CONTRIBUTION_TOKEN/)
assert.match(endpoint, /AI_CONTRIBUTION_RATE_LIMIT = 120/)
assert.match(endpoint, /prepare_contribution_guard\(/)
assert.match(endpoint, /apply_public_contribution\(/)
assert.match(endpoint, /valid_human_demonstration\(/)
assert.match(endpoint, /apply_human_demonstration\(/)
assert.match(endpoint, /totalHumanDemonstrations/)
assert.match(endpoint, /contribution_revision_stale/)
assert.match(endpoint, /normalized_contribution_guard\(\$current\)/)
assert.match(endpoint, /function valid_fresh_model\(/)
assert.match(endpoint, /state_contribution_epoch\(\$current\)/)
assert.match(endpoint, /contribution_epoch_mismatch/)
assert.match(endpoint, /\$action !== 'commit' && \$action !== 'reset'/)
assert.match(endpoint, /\$nextEpoch = state_contribution_epoch\(\$current\) \+ \(\$isKnowledgeReset \? 1 : 0\)/)
assert.match(endpoint, /\$nextGuard = \$isKnowledgeReset \? \['recent' => \[\], 'rates' => \[\]\]/)
assert.match(accessRules, /Require all denied/)
assert.match(endpointTest, /assert\.deepEqual\(finalEnvelope\.model\.championPolicy, initialModel\.championPolicy\)/)
assert.match(endpointTest, /assert\.equal\(finalEnvelope\.model\.totalGames, 6\)/)
assert.match(endpointTest, /assert\.equal\(afterHuman\.model\.totalHumanDemonstrations, 1\)/)
assert.match(endpointTest, /assert\.deepEqual\(afterHuman\.model\.policy, candidateBeforeHumanDemo\)/)
assert.match(endpointTest, /assert\.equal\(resetResult\.contributionEpoch, 2\)/)
assert.match(endpointTest, /assert\.equal\(legacyResult\.discarded, true\)/)
assert.match(endpointTest, /assert\.equal\(staleEpochResult\.error\.code, "contribution_epoch_mismatch"\)/)
assert.match(endpointTest, /assert\.equal\(invalidResetResponse\.status, 422\)/)
assert.match(index, /js\/00-constants\.js\?v=2\.5\.3/)
assert.match(index, /js\/06-menu-ai\.js\?v=2\.5\.3/)
assert.match(index, /js\/06-menu-ai-training\.js\?v=2\.5\.3/)
assert.match(index, /js\/08-main-loop\.js\?v=2\.5\.3/)

console.log("AI validation passed: bounded learning, frozen champion safety, public contributions, and epoch-isolated administrative resets are present.")
