const assert = require("node:assert/strict")
const fs = require("node:fs")
const path = require("node:path")

const root = path.resolve(__dirname, "..")
const read = relativePath => fs.readFileSync(path.join(root, relativePath), "utf8")

const ai = read("js/06-menu-ai.js")
const capabilities = read("js/01-ai-capabilities.js")
const training = read("js/06-menu-ai-training.js")
const input = read("js/09-input.js")
const tower = read("js/03-tower.js")
const projectile = read("js/04-support-entities.js")
const mainLoop = read("js/08-main-loop.js")
const endpoint = read("ai-learning.php")
const accessRules = read("data/.htaccess")
const endpointTest = read("tools/test-ai-endpoint.js")
const index = read("index.html")
const styles = read("styles.css")
const distributedCommon = read("tools/distributed-ai/common.js")
const distributedWorker = read("tools/distributed-ai/run-worker.js")
const distributedSelect = read("tools/distributed-ai/select-candidate.js")
const hostedModelTool = read("tools/distributed-ai/hosted-model.js")
const trainingWorkflow = read(".github/workflows/ai-training.yml")
const manualPromotionWorkflow = read(".github/workflows/ai-promote.yml")
const watchdogWorkflow = read(".github/workflows/ai-training-watchdog.yml")
const statusWorkflow = read(".github/workflows/ai-status.yml")
const ciWorkflow = read(".github/workflows/ci.yml")
const trainingModes = training.slice(training.indexOf("var AI_TRAINING_MODES"), training.indexOf("var AI_TRAINING_PROFILES"))
const manualAimAction = ai.slice(ai.indexOf("function advanceAIManualAimAction"), ai.indexOf("function deselectAITowers"))
const animate = mainLoop.slice(mainLoop.indexOf("function animate()"))
const decisionCollection = ai.slice(ai.indexOf("function collectAIDecisionSamples"), ai.indexOf("function collectAITacticalLearningObservations"))
const controllerFinalization = training.slice(training.indexOf("function finalizeAIControllersOnGameOver"), training.indexOf("function stopAITrainingTrueSelfPlay"))
const humanDemonstration = ai.slice(ai.indexOf("function createLocalHumanDemonstration"), ai.indexOf("function finalizeLocalMatchCollection"))
const humanApplication = endpoint.slice(endpoint.indexOf("function apply_human_demonstration"), endpoint.indexOf("function normalized_contribution_guard"))

assert.match(ai, /AI_LEARNING_SCHEMA_VERSION = 12/)
assert.match(ai, /AI_MODEL_FAMILY = "semantic-intent-spatial-recurrent-actor-critic-v4"/)
assert.match(ai, /AI_POLICY_HIDDEN_SIZE_1 = 64/)
assert.match(ai, /AI_POLICY_HIDDEN_SIZE_2 = 32/)
assert.match(ai, /AI_DECISION_STATE_INPUT_SIZE = 80/)
assert.match(ai, /AI_DECISION_CANDIDATE_INPUT_SIZE = 80/)
assert.match(ai, /AI_DECISION_CREDIT_VERSION = 3/)
assert.match(ai, /AI_DECISION_TD_STEPS = 4/)
assert.match(ai, /AI_DECISION_DISCOUNT_PER_SECOND = 0\.99/)
assert.match(ai, /AI_DECISION_MEMORY_SIZE = 16/)
assert.match(ai, /AI_DECISION_SURVIVAL_CLASS_COUNT = 4/)
assert.match(ai, /AI_MAX_PUBLIC_DECISION_SAMPLES = 12/)
assert.match(ai, /AI_MAX_PUBLIC_CONTRIBUTION_BYTES = 131072/)
assert.match(ai, /AI_MAX_DECISION_SAMPLE_AGE = 1000000/)
assert.match(ai, /AI_POLICY_PARAMETER_LIMIT = 4/)
assert.match(ai, /target = clamp\(reward, -0\.98, 0\.98\)/)
assert.match(ai, /outputDelta = error \* \(1 - prediction \* prediction\)/)
assert.match(ai, /clampAIPolicyParameter\(/)
assert.doesNotMatch(ai, /return clamp\(reward, -2\.1, 1\.6\)/)
assert.match(ai, /trainAIPolicy\(aiMatchTelemetry\.selectionFeatures/)
assert.match(ai, /function aiDecisionForward\(/)
assert.match(ai, /function trainAIDecision\(/)
assert.match(ai, /function scoreAIDecisionCandidate\(/)
assert.match(ai, /chosenCandidateFeatures:/)
assert.match(ai, /memoryIn:/)
assert.match(ai, /successorStateFeatures:/)
assert.match(ai, /successorMemory:/)
assert.match(ai, /function getAIFourStepDecisionTargets\(/)
assert.match(decisionCollection, /settleAITacticalDecision\(side, null, true\)[\s\S]*getAIFourStepDecisionTargets\(samples, terminalReward, aiLearning\.policy\)[\s\S]*trainAIDecision\(samples\[i\], targets\[i\]/)
assert.match(controllerFinalization, /withAIContext\(PLAYER_SIDE\.left,[\s\S]*finalizeAIMatchLearning\(\)[\s\S]*withAIContext\(PLAYER_SIDE\.right,[\s\S]*finalizeAIMatchLearning\(\)/)
assert.doesNotMatch(ai, /rejectedCandidateFeatures:/)
assert.match(ai, /function summarizeAIDecisionEntities\(/)
assert.match(ai, /function getAIFactualDecisionLocalReward\(/)
assert.match(ai, /var supplied = Array\.isArray\(contextFeatures\) \? contextFeatures : \[\]/)
assert.match(ai, /WStateToMemory:/)
assert.match(ai, /WMemoryToMemory:/)
assert.match(ai, /WMemoryToState:/)
assert.match(ai, /WValue:/)
assert.match(ai, /WSurvival:/)
assert.match(ai, /while\(getAIUTF8ByteLength\(JSON\.stringify\(contribution\)\) > AI_MAX_PUBLIC_CONTRIBUTION_BYTES/)
assert.match(ai, /decisionSamples: decisionSamples/)
assert.doesNotMatch(ai, /getAIDecisionBootstrapWeight\(familyIndex, policyOverride\) \* 2\.5/)
assert.match(ai, /score: \(forward \? forward\.score : 0\) \+ humanTacticalBonus \+ aiRandomWeight\(explorationScale\)/)
assert.match(ai, /entry\.decision\.counterLearningBonus = getAILoadoutCounterLearningBonus\(entry\.loadout\.key, observedLoadoutSummary\)[\s\S]{0,120}entry\.decision\.score \+= entry\.decision\.counterLearningBonus/)
assert.doesNotMatch(ai, /function shouldAIRush\(/)
assert.doesNotMatch(ai, /function getRushSendScore\(/)
assert.doesNotMatch(ai, /function getAIAimSnapshot\(/)
assert.doesNotMatch(ai, /getAIDecisionBootstrapWeight\(\)/)
assert.match(ai, /trainingSamples: aiCreateVector\(AI_DECISION_FAMILY_COUNT, 0\)/)
assert.match(ai, /decision\.trainingSamples\[familyIndex\]\+\+/)
assert.match(ai, /function recordAINoOpDecision\(/)
assert.match(ai, /actionableCandidates\.length == 0[\s\S]{0,120}recordAINoOpDecision\(bestNoOp\)/)
assert.match(ai, /familyCounts\[countIndex\] > 1/)
assert.doesNotMatch(ai, /canAIInvestInFarmNow/)
assert.match(ai, /function migrateAIPolicy\(/)
assert.match(ai, /function migrateAISchema10Decision\(/)
assert.match(ai, /function migrateAISchema11Decision\(/)
assert.match(ai, /resetDecisionTraining \? 0/)
assert.match(ai, /AI_CONTRIBUTION_STORAGE_KEY = "aiPendingContributionsV2"/)
assert.match(ai, /localStorage\.removeItem\("aiPendingContributionsV1"\)/)
assert.match(ai, /function queueAIPublicContribution\(/)
assert.match(ai, /function flushAIPublicContributionQueue\(/)
assert.match(ai, /createAIPublicMatchContribution\(aiLives, enemyLives, reward, matchFeatures, selfPlayActive\)/)
assert.match(ai, /queueAIPublicContribution\(publicContribution\)/)
assert.match(ai, /return isValidAIPolicy\(aiLearning\.policy\) \? aiLearning\.policy : aiLearning\.championPolicy/)
assert.match(ai, /eventType: "human-demo-v1"/)
assert.match(ai, /AI_MAX_HUMAN_TACTICAL_EVENTS = 128/)
assert.match(ai, /AI_MAX_CAPTURED_HUMAN_ACTIONS = 96/)
assert.match(ai, /AI_MAX_HUMAN_TACTICAL_TOWERS = 64/)
assert.match(humanDemonstration, /map: Math\.max\(0, Math\.floor\(Number\(mapNumber\) \|\| 0\)\)/)
assert.match(humanDemonstration, /durationMs: clamp\(Math\.ceil\(Math\.max\(0, gameNow\(\) - timeGameStarted\) \/ 250\) \* 250, 1, 7200000\)/)
assert.match(humanDemonstration, /events: getLocalHumanTacticalEventsForUpload\(side\)/)
assert.doesNotMatch(humanDemonstration, /model:|decisionSamples:|observations:/)
assert.match(ai, /function updateLocalMatchCollectionTelemetry\(/)
assert.match(ai, /function finalizeLocalMatchCollection\(/)
assert.match(ai, /function discardStaleAIPublicContributions\(/)
assert.match(ai, /contributionEpoch: Math\.max\(1, Math\.floor\(localMatchCollectionState\.contributionEpoch\)\)/)
assert.match(ai, /contributionEpoch: Math\.max\(1, Math\.floor\(aiMatchTelemetry\.contributionEpoch\)\)/)
assert.match(ai, /function applyAILearningEnvelope\(/)
assert.match(ai, /aiPersistenceState\.updatedAt = typeof parsed\.updatedAt/)
assert.match(ai, /incomingEpoch < aiPersistenceState\.contributionEpoch \|\| incomingEpoch == aiPersistenceState\.contributionEpoch && incomingRevision < aiPersistenceState\.revision/)
assert.match(ai, /aiLearningRefreshForceQueued = true/)
assert.match(ai, /code == "contribution_epoch_mismatch"[\s\S]{0,500}refreshAILearningFromBackend\(true\)/)
assert.match(ai, /code == "contribution_revision_stale"[\s\S]{0,700}refreshAILearningFromBackend\(true\)/)
assert.match(ai, /function markAIPublicContributionStatus\(/)
assert.match(ai, /contextTelemetry\.contributionStatus = status/)
assert.match(ai, /localMatchCollectionState\.contributionStatus = leftQueued && rightQueued \? "queued" : "failed"/)
assert.match(ai, /var candidateContext = aiContextsBySide\[aiTrainingState\.candidateSide\]/)
assert.match(ai, /var savedLearningSnapshot = JSON\.parse\(JSON\.stringify\(aiLearning\)\)/)
assert.match(ai, /aiPersistenceState\.revision = Math\.max\(aiPersistenceState\.revision, committedRevision\)/)
assert.match(ai, /var contributionMetadataCurrent = contributionEpoch >= aiPersistenceState\.contributionEpoch && contributionRevision >= aiPersistenceState\.revision/)
assert.match(ai, /selfPlayActive && typeof shouldAITrainingPublishContributions == "function"/)
assert.match(ai, /selectedMenuMode != "local" \|\| aiEnabled \|\| practiceMode \|\| bossMode/)
assert.match(mainLoop, /updateLocalMatchCollectionTelemetry\(\)/)
assert.match(mainLoop, /finalizeLocalMatchCollection\(\)/)
assert.match(mainLoop, /getCompletedMatchAIRematchMessage\(\)/)
assert.match(input, /recordLocalHumanTowerPlacement\(/)
assert.match(input, /recordLocalHumanTowerUpgrade\(/)
assert.match(input, /recordLocalHumanTowerSale\(/)
assert.match(input, /recordLocalHumanBloonSend\([^,]+, "manual"\)/)
assert.match(input, /recordLocalHumanEcoToggle\(/)
assert.match(input, /recordLocalHumanBoost\(/)
assert.match(input, /recordLocalHumanCollection\([^,]+, "bank"\)/)
assert.match(input, /recordLocalHumanAim\(/)
assert.match(mainLoop, /recordLocalHumanBloonSend\([^,]+, "auto"\)/)
assert.match(mainLoop, /recordLocalHumanCollection\([^,]+, "banana"\)/)

assert.match(ai, /championPolicy: cloneAIPolicy\(candidatePolicy\)/)
assert.match(ai, /populationPolicies: \[\]/)
assert.match(training, /policySnapshot: opponentPolicy/)
assert.match(training, /learningEnabled: false/)
assert.match(training, /candidateTrainingMatches >= 128/)
assert.match(training, /evaluationGames >= 64/)
assert.match(training, /score >= 0\.58/)
assert.match(training, /return \{ label: "Session Only", disabled: true, action: "none" \}/)
assert.match(training, /return \{ label: "Refreshing\.\.\.", disabled: true, action: "none" \}/)
assert.match(training, /return \{\s*label: "Live Eval"/)
assert.match(training, /if\(counts\[i\] > 0\)/)
assert.match(training, /aiTrainingState\.trueSelfPlayMatches >= getAITrainingGoalEpisodes\(\)/)
assert.match(training, /function installAITrainingHostedLearning\(/)
assert.match(training, /function activateAITrainingSessionModel\(/)
assert.match(training, /function deactivateAITrainingSessionModel\(/)
assert.match(training, /function getAITrainingPersistenceMode\(/)
assert.match(training, /function shouldAITrainingPublishContributions\(/)
assert.match(trainingModes, /id: "selfplay"/)
assert.doesNotMatch(trainingModes, /id: "synthetic"/)
assert.match(training, /aiTrainingState\.persistenceMode = persistenceMode/)
assert.match(training, /Model: Temporary 26,440-Parameter Intent-Spatial AC/)
assert.match(training, /return AI_CROSS_MATCH_LEARNING_ENABLED && aiPersistenceState\.contributionEnabled \? "contributions" : "session"/)
assert.doesNotMatch(training, /return "snapshot"/)
assert.match(training, /aiLearning\.policy = cloneAIPolicy\(aiLearning\.championPolicy\)/)
assert.match(training, /scenarioIndex = aiTrainingState\.trueSelfPlayMatches % 8/)
assert.match(training, /candidateSide = Math\.floor\(scenarioIndex \/ 2\) % 2 == 0/)
assert.match(training, /candidateResponds = Math\.floor\(scenarioIndex \/ 4\) % 2 == 0/)
assert.match(training, /Math\.floor\(bloonPathProgress \* 10\)/)
assert.match(training, /aiTrainingState\.candidateResponds = candidateResponds/)
assert.doesNotMatch(training, /chooseAITrainingRandomLoadout|chooseAITrainingBestLoadout|forcedLoadout/)
assert.match(training, /primeAITrainingTrueSelfPlayContext\(probeSide, null, null, probePolicyConfig\)/)
assert.match(distributedWorker, /candidateRole: aiTrainingState\.candidateResponds \? "responder" : "probe"/)
assert.match(distributedWorker, /validatePolicyOnlyCandidate\(checkpoint, baseline\)/)
assert.match(distributedWorker, /--mode migrate --checkpoint checkpoint\.json/)
assert.match(distributedWorker, /function validateMigrationSource\(/)
assert.match(distributedWorker, /function assertMigrationRetention\(/)
assert.match(distributedWorker, /mode: "migrate"/)
assert.match(distributedSelect, /requiredArg\(args, "baseline"\)/)
assert.match(distributedSelect, /materializeAggregatedPolicyCandidate\(results, baseline\)/)
assert.doesNotMatch(distributedSelect, /materializePolicyOnlyCandidate\(selected, baseline\)/)
assert.match(distributedCommon, /model\.championPolicy = clone\(selectedPolicy\)/)
assert.match(distributedCommon, /aggregateTrainResultPolicies\(results, baseline\)/)
assert.match(distributedCommon, /MODEL_SCHEMA_VERSION = 12/)
assert.match(distributedCommon, /MODEL_FAMILY = "semantic-intent-spatial-recurrent-actor-critic-v4"/)
assert.match(distributedCommon, /DECISION_STATE_INPUT_SIZE = 80/)
assert.match(distributedCommon, /DECISION_CANDIDATE_INPUT_SIZE = 80/)
assert.match(distributedCommon, /DECISION_CREDIT_VERSION = 3/)
assert.match(distributedCommon, /POLICY_PARAMETER_COUNT = 26440/)
assert.match(distributedCommon, /byRole: roles/)
assert.match(distributedCommon, /expectedCoverage\.balanced/)
assert.match(distributedCommon, /MAX_RECOVERED_STALLS = 3/)
assert.match(distributedCommon, /function maxRecoveredStalls\(matches\)/)
assert.match(distributedCommon, /Math\.max\(MAX_RECOVERED_STALLS, Math\.ceil\(matches \/ 8\)\)/)
assert.match(distributedWorker, /MAX_STALL_RECOVERIES_PER_MATCH = MAX_RECOVERED_STALLS/)
assert.match(distributedWorker, /aiTrainingState\.trueSelfPlayStallRecoveries != observedStalls/)
assert.match(distributedWorker, /Recovered discarded match/)
assert.match(distributedWorker, /observedStalls > maxRecoveredStalls\(requestedMatches\)/)
assert.match(distributedWorker, /Stall recovery limit exceeded during match/)
assert.doesNotMatch(distributedWorker, /state\.stalls > observedStalls \|\| state\.discarded/)

assert.match(ai, /return aiPlaceTower\([\s\S]*?!= null/)
assert.match(ai, /function getBaseTowerPriceByType\(towerType\) \{\s*return typeof BASE_TOWER_PRICES\[towerType\] == "number" \? BASE_TOWER_PRICES\[towerType\] : 100/)
assert.match(ai, /function getLearnedFarmerPlacementOption\(side, matchup\) \{\s*var farms = getSideTowersByType\(side, "farm"\)[\s\S]{0,400}if\(!needsFarmer\) return null/)
assert.match(ai, /if\(tower\.towerType == "farmer"\) continue\s*if\(isAITowerSaleProtected\(tower\)\) continue/)
assert.match(ai, /if\(restrictToEmergency && \(towerType == "farm" \|\| towerType == "farmer" \|\| role == "farm" \|\| role == "farmer"\)\)/)
assert.match(ai, /type: "place",\s*image: image,\s*targetX: spot\.x,\s*targetY: spot\.y/)
assert.match(ai, /aiRequestPlaceTowerImage\(side, option\.image, priority, option\.decisionSample, option\.targetX, option\.targetY\)/)
assert.match(ai, /function isAITowerSaleProtected\(tower\)/)
assert.match(ai, /function aiTrySellTower\(side, tower\) \{\s*if\(!tower \|\| tower\.playerSide != side \|\| isAITowerSaleProtected\(tower\)\)/)
assert.match(ai, /function aiRequestSellTower\(side, tower, priority, decisionSample\) \{\s*if\(!tower \|\| tower\.playerSide != side \|\| isAITowerSaleProtected\(tower\)\)/)
assert.match(ai, /function aiPlaceFarmer\(side, x, y\) \{\s*if\(getSideTowersByType\(side, "farm"\)\.length == 0/)
assert.match(ai, /getBestTowerUpgradeOption\(side, matchup, defenseMath, true\)/)
assert.match(ai, /if\(matchup\.dangerHigh && matchup\.defenseMath\.requiredDps > matchup\.defenseMath\.currentDps \* 1\.02\) \{\s*tryPlaceEmergencyDefense\(side, matchup\)\s*return/)
assert.match(ai, /function isAIPaidActionPending\(\) \{[\s\S]{0,220}action\.type == "placeTower" \|\| action\.type == "upgradeTower" \|\| action\.type == "sellTower"/)
assert.doesNotMatch(ai.slice(ai.indexOf("function isAIPaidActionPending"), ai.indexOf("function runAIGameplayDecisionCycle")), /placeFarmer/)
assert.match(ai, /directUpgradeSucceeded = aiTryUpgradeTower\(/)
assert.match(ai, /return directUpgradeSucceeded/)
assert.match(ai, /function isAITrainingDirectAIActionMode\(\)[\s\S]{0,180}isAITrainingTrueSelfPlayActive\(\)/)
assert.doesNotMatch(ai, /function isAITrainingDirectAIActionMode\(\) \{\s*return gameStarted/)
assert.match(ai, /manualAimAction: null/)
assert.match(manualAimAction, /getSelectedTower\(side\) != tower/)
assert.match(manualAimAction, /updateTowerTargetPriority\(tower, 1\)/)
assert.match(mainLoop, /function updateManualAimTowerTargets\(\)/)
assert.match(animate, /updateManualAimTowerTargets\(\)/)
assert.doesNotMatch(ai, /function lockTowerAimToCursor\(/)
assert.match(ai, /towerID: tower\.towerID/)
assert.match(ai, /action\.attempts >= 2/)
assert.match(ai, /currentUpgrade == 4[\s\S]*?hasOtherTier5/)
assert.match(input, /typeof upgradeCost != "number"/)
assert.match(input, /addEventListener\("pointerdown", handleCanvasPointerDown\)/)
assert.doesNotMatch(input, /addEventListener\("mousedown"/)

assert.match(ai, /var noActiveThreat = defenseMath\.requiredDps <= 0/)
assert.match(ai, /aiSelectEcoSend\(side, matchup\)/)
assert.doesNotMatch(ai, /getAITacticalActionBonus\(side, "(?:eco|rush)"/)
assert.doesNotMatch(ai, /getAITacticalActionBonus\(side, tower\.towerType == "farm"/)
assert.match(ai, /finalizeAITacticalLearning\(aiSide, reward\)/)
assert.match(ai, /runAIGameplayDecisionCycle/)
assert.match(training, /runAIGameplayDecisionCycle\(aiSide\)/)

assert.match(ai, /if\(now <= sample\.lastSeenAt\)/)
assert.doesNotMatch(training, /function runAIForActiveContext\(\)[\s\S]{0,500}updateAITowerDamageRates\(\)/)
assert.match(training, /if\(isAITrainingTrueSelfPlayActive\(\)\) \{\s*updateAITowerDamageRates\(\)/)

assert.match(tower, /var nextTowerID = 1/)
assert.match(tower, /this\.towerID = nextTowerID\+\+/)
assert.doesNotMatch(tower, /this\.towerID = Math\.trunc\(Math\.random/)
assert.match(projectile, /this\.sourceImage = image/)
assert.match(input, /players\[side\]\.money -= baseFarmerPrice/)
assert.match(mainLoop, /p1lives -= 104/)
assert.match(mainLoop, /p2lives -= 104/)

assert.match(endpoint, /AI_MODEL_SCHEMA = 12/)
assert.match(endpoint, /AI_POLICY_FORMAT_VERSION = 2/)
assert.match(endpoint, /AI_DECISION_STATE_INPUT = 80/)
assert.match(endpoint, /AI_DECISION_CANDIDATE_INPUT = 80/)
assert.match(endpoint, /AI_SCHEMA10_DECISION_CANDIDATE_INPUT = 40/)
assert.match(endpoint, /AI_DECISION_CREDIT_VERSION = 3/)
assert.match(endpoint, /AI_MAX_DECISION_SAMPLES = 12/)
assert.match(endpoint, /AI_MAX_CONTRIBUTION_POLICY_DELTA_NORM = 0\.35/)
assert.match(endpoint, /AI_MAX_SAFE_INTEGER = 9007199254740991/)
assert.match(endpoint, /function migrate_legacy_model\(/)
assert.match(endpoint, /function migrate_schema9_model\(/)
assert.match(endpoint, /function migrate_schema10_model\(/)
assert.match(endpoint, /function valid_schema10_model\(/)
assert.match(endpoint, /function migrate_schema11_model\(/)
assert.equal((endpoint.match(/strip_reserved_human_priors\(\$model\);/g) || []).length, 4)
assert.match(endpoint, /function valid_schema11_model\(/)
assert.match(endpoint, /AI_DECISION_STATE_INPUT - AI_SCHEMA11_DECISION_STATE_INPUT/)
assert.match(endpoint, /AI_DECISION_CANDIDATE_INPUT - AI_SCHEMA11_DECISION_CANDIDATE_INPUT/)
assert.match(endpoint, /function migrate_schema11_model[\s\S]{0,500}\$model\['placementStats'\] = \[\];[\s\S]{0,100}\$model\['loadoutPlacementStats'\] = \[\];/)
assert.match(endpoint, /function valid_schema9_model\(/)
assert.match(endpoint, /function train_candidate_decision\(/)
assert.match(endpoint, /function decision_four_step_targets\(/)
assert.match(endpoint, /function valid_legacy_decision_sample\(/)
assert.match(endpoint, /chosenCandidateFeatures/)
assert.match(endpoint, /rejectedCandidateFeatures/)
assert.match(endpoint, /WStateToMemory/)
assert.match(endpoint, /WMemoryToMemory/)
assert.match(endpoint, /WMemoryToState/)
assert.match(endpoint, /WSurvival/)
assert.match(endpoint, /function limit_policy_parameter_delta\(/)
assert.match(endpoint, /function canonical_weight\(/)
assert.match(endpoint, /function canonical_digest_encode\(/)
assert.match(endpoint, /return 's:' \. bin2hex\(\$value\)/)
assert.match(distributedCommon, /bytes\.writeDoubleBE\(item\)/)
assert.match(endpoint, /if \(\$origin === ''\) \{\s*return false;/)
assert.match(endpoint, /expectedRevision/)
assert.match(endpoint, /revision_conflict/)
assert.match(endpoint, /X_AI_TRAINER_KEY/)
assert.match(endpoint, /LOCK_EX/)
assert.match(endpoint, /rename\(\$temporaryFile, \$stateFile\)/)
assert.match(endpoint, /payload_too_large/)
assert.match(endpoint, /action === 'contribute'/)
assert.match(endpoint, /X_AI_CONTRIBUTION_TOKEN/)
assert.match(endpoint, /AI_CONTRIBUTION_RATE_LIMIT = 120/)
assert.match(endpoint, /prepare_contribution_guard\(/)
assert.match(endpoint, /apply_public_contribution\(/)
assert.match(endpoint, /valid_human_demonstration\(/)
assert.match(endpoint, /apply_human_demonstration\(/)
assert.match(endpoint, /totalHumanDemonstrations/)
assert.match(endpoint, /\$store !== 'tacticalFamilyStats' \|\| strpos\(\$key, 'human\|'\) !== 0/)
assert.match(endpoint, /hash_equals\(model_digest\(\$decoded\['model'\]\), \$decoded\['modelDigest'\]\)/)
assert.match(endpoint, /strpos\(\$key, 'human\|'\) === 0/)
assert.match(humanApplication, /update_score_record\(\$model\['tacticalFamilyStats'\]/)
assert.match(humanApplication, /prune_score_store\(\$model\['tacticalFamilyStats'\]/)
assert.doesNotMatch(humanApplication, /playerProfile|loadoutStats|loadoutCounterStats|totalLoadoutSamples|\['policy'\]|championPolicy|populationPolicies/)
assert.match(endpoint, /contribution_revision_stale/)
assert.match(endpoint, /normalized_contribution_guard\(\$current\)/)
assert.match(endpoint, /function valid_fresh_model\(/)
assert.match(endpoint, /state_contribution_epoch\(\$current\)/)
assert.match(endpoint, /contribution_epoch_mismatch/)
assert.match(endpoint, /\$action === 'promote'/)
assert.match(endpoint, /HTTP_X_AI_POLICY_PROMOTION_KEY/)
assert.match(endpoint, /function promotion_base_digest\(/)
assert.match(endpoint, /\$candidatePolicyPreserved = model_digest\(\$currentModel\['policy'\]\) !== \$request\['expectedPolicyDigest'\]/)
assert.match(endpoint, /\$nextModel = \$currentModel/)
assert.match(endpoint, /normalized_contribution_guard\(\$current\), \$currentEpoch/)
assert.match(endpoint, /\$action !== 'commit' && \$action !== 'reset'/)
assert.match(endpoint, /\$nextEpoch = state_contribution_epoch\(\$current\) \+ \(\$isKnowledgeReset \? 1 : 0\)/)
assert.match(endpoint, /\$nextGuard = \$isKnowledgeReset \? \['recent' => \[\], 'rates' => \[\]\]/)
assert.match(endpoint, /\['recent' => \[\], 'rates' => \[\]\],\s*\$epoch \+ 1/)
assert.match(accessRules, /Require all denied/)
assert.match(endpointTest, /assert\.equal\(migratedState\.revision, 8\)/)
assert.match(endpointTest, /assert\.equal\(migratedState\.contributionEpoch, 5\)/)
assert.match(endpointTest, /createHostedSnapshot\(envelope\)/)
assert.match(endpointTest, /\.status, 429/)
assert.match(endpointTest, /const staleEpoch = createContribution/)
assert.match(endpointTest, /migratedChampion\.decision\[key\], schema10Model\.championPolicy\.decision\[key\]/)
assert.match(endpointTest, /assert\.equal\(envelope\.model\.totalDecisionSamples, 1\)/)
assert.match(endpointTest, /createLegacyDecisionSample\(\)/)
assert.match(endpointTest, /assert\.equal\(envelope\.model\.totalHumanDemonstrations, 3\)/)
assert.match(endpointTest, /assert\.deepEqual\(envelope\.model\.policy, candidateBeforeHuman\)/)
assert.match(endpointTest, /assert\.deepEqual\(envelope\.model\.playerProfile, profileBeforeHuman\)/)
assert.match(endpointTest, /assert\.deepEqual\(envelope\.model\.loadoutStats, loadoutStatsBeforeHuman\)/)
assert.match(endpointTest, /assert\.deepEqual\(envelope\.model\.loadoutCounterStats, loadoutCounterStatsBeforeHuman\)/)
assert.match(endpointTest, /forgedHumanPrior[\s\S]{0,300}human\|rush\|send\|2[\s\S]{0,200}\.status, 422/)
assert.match(endpointTest, /assert\.equal\(resetResult\.contributionEpoch, migratedEpoch \+ 1\)/)
assert.match(endpointTest, /assert\.equal\(promoteResult\.candidatePolicyPreserved, true\)/)
assert.match(endpointTest, /assert\.equal\(\(await replayPromotion\.json\(\)\)\.duplicate, true\)/)
assert.match(endpointTest, /assert\.equal\(finalEnvelope\.model\.totalDecisionSamples, 4\)/)
assert.match(endpointTest, /assert\.deepEqual\(finalEnvelope\.model\.championPolicy, resetChampion\)/)
assert.match(distributedCommon, /function createHostedSnapshot\(/)
assert.match(distributedCommon, /function buildPolicyPromotionRequest\(/)
assert.match(hostedModelTool, /AI_POLICY_PROMOTION_KEY/)
assert.match(hostedModelTool, /redirect: "error"/)
assert.match(trainingWorkflow, /name: ai-hosted-baseline/)
assert.match(trainingWorkflow, /publish-hosted:/)
assert.match(trainingWorkflow, /--baseline "\$RUNNER_TEMP\/bundle\/baseline\.json"/)
assert.doesNotMatch(trainingWorkflow, /--checkpoint training\/checkpoints\/champion\.json/)
assert.match(trainingWorkflow, /run-name:.*Continuous AI training for/)
assert.match(trainingWorkflow, /expected_sha:/)
assert.match(trainingWorkflow, /expectedSha !== process\.env\.EVENT_SHA/)
assert.match(trainingWorkflow, /head_sha="\$EXPECTED_SHA" -f status=success/)
assert.doesNotMatch(trainingWorkflow, /\n  continue:/)
assert.doesNotMatch(trainingWorkflow, /gh workflow run ai-training\.yml/)
assert.match(trainingWorkflow, /handoff-continuous-training:/)
assert.match(trainingWorkflow, /needs: \[prepare, train, select, evaluate, report, promote, publish-hosted, finalize-promotion\]/)
assert.match(trainingWorkflow, /gh workflow run ai-training-watchdog\.yml[\s\S]*completed_training_run_id="\$GITHUB_RUN_ID"/)
assert.match(trainingWorkflow, /finalize-promotion:[\s\S]*permissions:\s*\n\s*actions: write\s*\n\s*contents: write\s*\n\s*pull-requests: write/)
assert.match(trainingWorkflow, /actions\/runs\/\$approval_run\/approve/)
assert.match(trainingWorkflow, /\.path == "\.github\/workflows\/ci\.yml"[\s\S]*\.actor\.login == "github-actions\[bot\]"[\s\S]*\.pull_requests\[0\]\.head\.sha == \$sha/)
assert.match(manualPromotionWorkflow, /publish-hosted:/)
assert.match(manualPromotionWorkflow, /AI_POLICY_PROMOTION_KEY/)
assert.match(manualPromotionWorkflow, /reconcile_hosted_promotion:/)
assert.match(manualPromotionWorkflow, /mode=reconcile/)
assert.match(manualPromotionWorkflow, /finalize-promotion:[\s\S]*permissions:\s*\n\s*actions: write\s*\n\s*contents: write\s*\n\s*pull-requests: write/)
assert.match(manualPromotionWorkflow, /actions\/runs\/\$approval_run\/approve/)
assert.match(manualPromotionWorkflow, /\.path == "\.github\/workflows\/ci\.yml"[\s\S]*\.actor\.login == "github-actions\[bot\]"[\s\S]*\.pull_requests\[0\]\.head\.sha == \$sha/)
assert.match(watchdogWorkflow, /AI_HOSTED_PROMOTION_ENABLED == 'true'/)
assert.match(watchdogWorkflow, /training_matches=192/)
assert.match(watchdogWorkflow, /cron: "2-59\/5 \* \* \* \*"/)
assert.match(watchdogWorkflow, /sort_by\(\.created_at, \.id\) \| reverse/)
assert.match(watchdogWorkflow, /Date\.parse\(run\.updated_at\)/)
assert.match(watchdogWorkflow, /Math\.max\(\.\.\.completed\)\+30\*60\*1000/)
assert.match(watchdogWorkflow, /Failure cooldown active/)
assert.match(watchdogWorkflow, /matching-refs\/heads\/ai-promotion/)
assert.match(watchdogWorkflow, /workflows: \[CI, Distributed AI Training\]/)
assert.match(watchdogWorkflow, /head_sha="\$current_sha" -f status=success/)
assert.match(watchdogWorkflow, /actions\/runs\/\$run_id\/cancel/)
assert.match(watchdogWorkflow, /expected_sha="\$current_sha"/)
assert.match(watchdogWorkflow, /completed_training_run_id:/)
assert.match(watchdogWorkflow, /\.name == "handoff-continuous-training"/)
assert.match(watchdogWorkflow, /"\$COMPLETED_TRAINING_RUN_ID" != "\$source_run_id"/)
assert.match(watchdogWorkflow, /select\(\$handoff == "" or \(\.id \| tostring\) != \$handoff\)/)
assert.match(watchdogWorkflow, /active=\$\(gh api[\s\S]{0,600}'\[\.workflow_runs\[\] \| select\(\.status != "completed"\) \| select\(\$handoff == "" or \(\.id \| tostring\) != \$handoff\)\]'/)
assert.match(watchdogWorkflow, /Manual or externally coordinated AI training is active; waiting for it to finish\./)
assert.match(watchdogWorkflow, /Checkpoint-only main update belongs to its active training transaction/)
assert.match(watchdogWorkflow, /gh workflow run ai-status\.yml[\s\S]*training_run_id="\$run_id"/)
assert.match(watchdogWorkflow, /Scheduled reconciliation will retry training run/)
assert.equal((watchdogWorkflow.match(/gh workflow run ai-training\.yml/g) || []).length, 1)
assert.match(statusWorkflow, /cron: "\*\/5 \* \* \* \*"/)
assert.match(statusWorkflow, /workflow_dispatch:[\s\S]*training_run_id:/)
assert.match(statusWorkflow, /types: \[requested, in_progress, completed\]/)
assert.match(statusWorkflow, /actions: read[\s\S]*contents: write/)
assert.match(statusWorkflow, /ref: main[\s\S]*persist-credentials: false/)
assert.match(statusWorkflow, /node tools\/distributed-ai\/training-status\.js/)
assert.match(ciWorkflow, /uses: raven-actions\/actionlint@[0-9a-f]{40}/)
assert.match(ciWorkflow, /version: 1\.7\.12/)
assert.match(index, /js\/00-constants\.js\?v=2\.6\.0&amp;balance=farmer-free/)
assert.match(index, /js\/01-ai-capabilities\.js\?v=2\.6\.0&amp;schema=12/)
assert.match(capabilities, /var AI_CAPABILITY_KEYS = \[/)
assert.match(capabilities, /"manualFollow"/)
assert.match(capabilities, /"manualLock"/)
assert.match(capabilities, /function getNormalizedAICapabilityVector\(/)
assert.match(ai, /capabilityFacts: getAILoadoutCapabilityFacts\(entry\.loadout\.towers, entry\.loadout\.boosts, 0\)/)
assert.equal((ai.match(/capabilityFacts: getAILoadoutCapabilityFacts\(strategy\.towers, strategy\.boosts,/g) || []).length, 2)
assert.match(index, /meta name="viewport" content="width=device-width, initial-scale=1"/)
assert.match(index, /js\/06-menu-ai\.js\?v=2\.6\.0&amp;schema=12/)
assert.match(index, /js\/06-menu-ai-training\.js\?v=2\.6\.0&amp;schema=12/)
assert.match(index, /js\/08-main-loop\.js\?v=2\.6\.0&amp;schema=12/)
assert.match(index, /js\/09-input\.js\?v=2\.6\.0&amp;schema=12/)
assert.match(styles, /@media \(max-aspect-ratio: 683 \/ 384\)/)
assert.match(styles, /@media \(min-aspect-ratio: 683 \/ 384\)/)
assert.match(styles, /touch-action: none/)

console.log("AI validation passed: schema-12 intent-spatial candidates, bounded human tactical priors, four-step actor-critic credit, and continuous-training safety are present.")
